### ISSUE TITLE
Need some open source Algorithms (SEE description)

### ISSUE THREAD

**Issue by SanjayDevTech** [SanjayDevTech/Code-with-love#1]
## Algorithms
- Palindrome
- Prime Number check
- Armstrong number
- Printing pattern
etc....

### username_program.extension

**Comment by sejalshri** [comment]
@SanjayDevTech hey.  i would like to add algorithms for  palindrome ,prime number check and Armstrong number in cpp.

**Comment by lucasguiss** [comment]
@SanjayDevTech I would like to add some algorithms in Go. Can I?

**Comment by SanjayDevTech** [comment]
Yeah sure... These issues are open to all...

But filename should be in the above format

**Comment by Agung-Krisna** [comment]
I would like to try to add the Palindrome algorithm in C

**Comment by kishanpython** [comment]
I would like to add prime number related program in python.

**Comment by ishi0301** [comment]
I would love to do this in c++.please assign me.

**Comment by SanjayDevTech** [comment]
These issues are open to all...
😃

**Comment by keerti2001** [comment]
Sir, I have added the Binary Search program under C language and made a pull request

**Comment by akshay399** [comment]
i would like to add some printing pattern algorithms using python, may i?

**Comment by ReoCorreia** [comment]
Hey @SanjayDevTech  I would like to add some graphics algorithms in cpp

**Comment by shrey-3108** [comment]
i would like to add some more printing patterns using cpp

**Comment by darkcocoa** [comment]
@SanjayDevTech I would like add a program in Java for Armstrong Number. Can I do that please?
