### ISSUE TITLE
Need good CODE OF CONDUCT

### ISSUE THREAD

**Issue by SanjayDevTech** [SanjayDevTech/Code-with-love#32]
Anyone with good writing skills, help this repo by contributing CODE OF CONDUCT page.
😃 Thank you

**Comment by sujata13** [comment]
Can I add Code of Conduct Page?

**Comment by SanjayDevTech** [comment]
sure @sujata13

**Comment by sujata13** [comment]
Created PR for this issue. please check it and do let me know if any changes are required. Thanks.
