### ISSUE TITLE
Github actions bot needed (SEE DESCRIPTION)

### ISSUE THREAD

**Issue by SanjayDevTech** [SanjayDevTech/Code-with-love#80]
This repository needs a greeting github bot using Github actions
It should:
- Greet first contributor

**Thank you**

**Comment by iampavangandhi** [comment]
@SanjayDevTech Can I take this issue?

**Comment by SanjayDevTech** [comment]
😃 Sure thanks...
I just need a bot which greets the new contributors

I tried to make it myself,but it shows
```
Error: Resource not accessible by integration
```

**Comment by iampavangandhi** [comment]
@SanjayDevTech we can integrate ```greet-contributors-action``` from the github marketplace

**Comment by SanjayDevTech** [comment]
Sure if it is possible we can make

**Comment by SanjayDevTech** [comment]
@iampavangandhi  Thank you for your contributions....
Is it possible to change the message?

**Comment by iampavangandhi** [comment]
@SanjayDevTech Yes you can edit the message [check custom content](https://github.com/ibakshay/greet-contributors-action)

**Comment by SanjayDevTech** [comment]
@iampavangandhi I got it.
Thank you so much
